name: Deploy Hiking Bot

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Deploy prod
        env:
          PROD_TARGET_DIR: ${{ vars.PROD_TARGET_DIR }}
        run: zsh ./scripts/deploy-prod.sh

  deploy-test:
    if: github.ref == 'refs/heads/develop'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Deploy test
        env:
          TEST_TARGET_DIR: ${{ vars.TEST_TARGET_DIR }}
        run: zsh ./scripts/deploy-test.sh
