name: Deploy Hiking Bot

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Deploy prod
        env:
          PROD_TARGET_DIR: ${{ vars.PROD_TARGET_DIR }}
          REPO_URL: https://github.com/${{ github.repository }}.git
          GIT_BRANCH: main
        shell: cmd
        run: .\scripts\deploy-prod.cmd

  deploy-test:
    if: github.ref == 'refs/heads/develop'
    runs-on: self-hosted
    steps:
      - name: Deploy test
        env:
          TEST_TARGET_DIR: ${{ vars.TEST_TARGET_DIR }}
          REPO_URL: https://github.com/${{ github.repository }}.git
          GIT_BRANCH: develop
        shell: cmd
        run: .\scripts\deploy-test.cmd
